### ISSUE TITLE
Unrecognized option for as --64

### ISSUE THREAD

**Issue by kruger** [MentorEmbedded/nvptx-tools#23]
I'm trying to compile `gcc-7.3.0` using nvptx-tools and get the following error:
```
make[2]: Entering directory '/scr_ivy/kruger/upstream/gcc_build_202005/build-nvptx-gcc/gcc'
g++ -c   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W
-Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-lo
ng-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -DGENERATOR_FILE -fno-PIE -I. -Ibuild -I../
../gcc-7.3.0/gcc -I../../gcc-7.3.0/gcc/build -I../../gcc-7.3.0/gcc/../include  -I../../gcc-7.3.0/gcc/../libcpp/inc
lude  \
        -o build/genmddeps.o ../../gcc-7.3.0/gcc/genmddeps.c
/scr_ivy/kruger/contrib-gcc-openmp/nvptx-none/bin/as: unrecognized option '--64'
ptxas build/genmddeps.o, line 1; fatal   : Missing .version directive at start of file 'build/genmddeps.o'
ptxas fatal   : Ptx assembly aborted due to errors
nvptx-as: ptxas returned 255 exit status
Makefile:2594: recipe for target 'build/genmddeps.o' failed
make[2]: *** [build/genmddeps.o] Error 1
```

My configure for gcc is this:
```
../gcc-7.3.0/configure \
    --target=nvptx-none \
    --with-build-time-tools=$install_dir/nvptx-none/bin \
    --enable-as-accelerator-for=$target \
    --disable-sjlj-exceptions \
    --enable-newlib-io-long-long \
    --enable-languages="c,c++,fortran,lto" \
    --prefix=$install_dir
```

I not 100% sure this is an nvptx-tools issue, but it seems to me that g++ will always pass --64 as a standard flag to as and nvptx-tools/bin/as should be able handle it.

**Comment by tschwinge** [comment]
I just remembered that I'd once seen this error myself.  That took a while to track down...  The problem was that my `PATH` environment variale contained an "empty component": `PATH=[...]::[...]` or `PATH=[...]:`.  That means to the shell to find programs in the current directory.  That means that during the nvptx target GCC build, when GCC builds its own helper build-time tools (for example, `build/genmddeps.o`, as you've shown), it erroneously finds the `[build-gcc-offload-nvptx]/gcc/as` wrapper shell script (which invokes the nvptx `[install-gcc-offload-nvptx]/bin/as`), and this -- obviously -- is wrong for the GCC build tools.

Will you please verify your `PATH` environment variable?  If that's the same problem, then this isn't a nvptx-tools issue but rather a shell vs. `PATH` environment variable (vs. GCC?) issue.

If your `PATH` environment variable is not the origin of the problem, then please re-open this issue.
